# Generated by Django 6.0.3 on 2026-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=10)),
                ('grau', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('objetivos', models.TextField()),
                ('ects_total', models.IntegerField()),
                ('duracao_anos', models.IntegerField()),
                ('url_oficial', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='licenciaturas/')),
                ('departamento', models.CharField(max_length=200)),
            ],
        ),
    ]
