# Generated by Django 6.0.3 on 2026-04-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='grau',
            field=models.CharField(choices=[('LIC', 'Licenciatura'), ('PG', 'Pós-Graduação'), ('MST', 'Mestrado'), ('DOT', 'Doutoramento')], max_length=50),
        ),
    ]
