# Generated by Django 6.0.3 on 2026-04-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_licenciatura_grau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciatura',
            name='logo',
        ),
    ]
