# Generated by Django 6.0.3 on 2026-04-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_licenciatura_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('url_pagina_lusofona', models.URLField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/')),
                ('departamento', models.CharField(max_length=200)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('url_ciencia_vitae', models.URLField(blank=True, null=True)),
                ('url_orcid', models.URLField(blank=True, null=True)),
                ('url_pure', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='licenciatura',
            name='grau',
        ),
    ]
