# Generated by Django 6.0.3 on 2026-04-05 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_docente_remove_licenciatura_grau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='resumo',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='url_ciencia_vitae',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='url_orcid',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='url_pure',
        ),
    ]
