# Generated by Django 6.0.3 on 2026-04-05 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_docente_departamento_remove_docente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('url_oficial', models.URLField(blank=True, null=True)),
                ('nivel_interesse', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('ects', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ucs/')),
            ],
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='duracao_anos',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='ects_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='url_oficial',
            field=models.URLField(blank=True, null=True),
        ),
    ]
