# Generated by Django 6.0.3 on 2026-04-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_tecnologia_unidadecurricular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('conceitos_aplicados', models.TextField(blank=True, null=True)),
                ('url_github', models.URLField(blank=True, null=True)),
                ('url_demo', models.URLField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
