# Generated by Django 6.0.3 on 2026-04-05 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField(blank=True, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('area_tematica', models.CharField(max_length=200)),
                ('url_repositorio', models.URLField(blank=True, null=True)),
                ('nivel_interesse', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='tfcs/')),
            ],
        ),
    ]
