# Generated by Django 6.0.3 on 2026-04-05 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_tfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nivel', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AlterField(
            model_name='tfc',
            name='resumo',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
