# Generated by Django 6.0.3 on 2026-04-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_competencia_alter_tfc_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Estágio', 'Estágio')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
