# Generated by Django 6.0.3 on 2026-04-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_experienciaprofissional'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('decisoes', models.TextField(blank=True, null=True)),
                ('erros_correcoes', models.TextField(blank=True, null=True)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('entidade_referida', models.CharField(blank=True, max_length=200)),
                ('foto_papel', models.ImageField(blank=True, null=True, upload_to='making_of/')),
                ('uso_ia', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
