# Generated by Django 6.0.3 on 2026-04-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_makingof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('certificado_url', models.URLField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Mestrado', 'Mestrado'), ('Curso de Curta Duração', 'Curso de Curta Duração'), ('Workshop', 'Workshop')], max_length=50)),
            ],
        ),
    ]
