# Generated by Django 6.0.3 on 2026-04-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_formacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='formacoes',
            field=models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.formacao'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='projetos',
            field=models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.projeto'),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='competencias',
            field=models.ManyToManyField(blank=True, related_name='experiencias', to='portfolio.competencia'),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='experiencias', to='portfolio.tecnologia'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='portfolio.unidadecurricular'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.tecnologia'),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='ucs', to='portfolio.docente'),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='licenciatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ucs', to='portfolio.licenciatura'),
        ),
    ]
