# Generated by Django 6.0.3 on 2026-04-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_competencia_formacoes_competencia_projetos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacao',
            name='certificado_url',
        ),
        migrations.AddField(
            model_name='formacao',
            name='certificado',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
