# Generated by Django 6.0.3 on 2026-04-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_formacao_certificado_url_formacao_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ambito',
            field=models.CharField(choices=[('academico', 'Académico'), ('pessoal', 'Pessoal'), ('profissional', 'Profissional'), ('freelance', 'Freelance'), ('outro', 'Outro')], default='academico', max_length=50),
        ),
    ]
