# Generated by Django 6.0.3 on 2026-04-05 23:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_projeto_ambito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfc',
            name='area_tematica',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='tfc',
            name='url_repositorio',
        ),
        migrations.AddField(
            model_name='tfc',
            name='areas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='licenciatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.licenciatura'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='orientadores',
            field=models.ManyToManyField(blank=True, related_name='tfcs_orientados', to='portfolio.docente'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='palavras_chave',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='parceiro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tfc',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='nivel_interesse',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
