# Generated by Django 6.0.3 on 2026-04-06 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_tfc_area_tematica_remove_tfc_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadecurricular',
            name='licenciatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ucs', to='portfolio.licenciatura'),
        ),
    ]
