# Generated by Django 6.0.3 on 2026-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_unidadecurricular_licenciatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadecurricular',
            name='ano_curricular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='apresentacao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='bibliografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='conteudos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='semestre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
