# Generated by Django 6.0.3 on 2026-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_unidadecurricular_ano_curricular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='licenciatura',
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='licenciaturas',
            field=models.ManyToManyField(blank=True, related_name='ucs', to='portfolio.licenciatura'),
        ),
    ]
